AppMVC/Areas/Blog/Controllers/ViewPostController.cs
using AppMVC.Models;
using AppMVC.Models.Blog;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AppMVC.Areas.Blog.Controllers
{
    [Area("Blog")]
    public class ViewPostController : Controller
    {
        private readonly AppDBContext _context;
        private readonly ILogger<ViewPostController> _logger;

        public ViewPostController(AppDBContext context, ILogger<ViewPostController> logger)
        {
            _context = context;
            _logger = logger;
        }

        [Route("/post/{categoryslug?}")]
        public IActionResult Index([FromRoute(Name = "categoryslug")] string slug, [FromQuery(Name = "p")] int currentPage, [FromQuery] int size = 5)
        {
            ViewBag.categories = getCategories();
            ViewBag.slug = slug;
            Category caterogy = null;
            if (!string.IsNullOrEmpty(slug))
            {
                caterogy = _context.Categories
                    .Include(c => c.CategoryChildren)
                    .FirstOrDefault(c => c.Slug == slug);

                if (caterogy == null)
                {
                    return Content("Not Found Category");
                }

            }

            ViewBag.category = caterogy;

            //paging
            int totalPost;
            PagingModel pagingModel;
            var posts = _context.Posts
                .Include(p => p.Author)
                .Include(p => p.PostCategories)
                .ThenInclude(pc => pc.Category)
                .Include(p => p.PostImages)
                .AsQueryable();

            posts.OrderByDescending(p => p.DateUpdated);

            if (caterogy != null)
            {
                List<int> ids = new List<int>();
                ids.Add(caterogy.Id);
                caterogy.getCategoryChildIDs(ref ids);
             
                posts = _context.PostCategories
                    .Include(pc => pc.Post)
                    .ThenInclude(p => p.Author)
                    .Include(pc => pc.Post)
                    .ThenInclude(p => p.PostImages)
                    .Where(pc => ids.Contains(pc.CategoryID))
                    .Select(pc => pc.Post);
            }


            //paging
            totalPost = posts.Count();
            pagingModel = new(currentPage, totalPost, size, Url.Action("Index"));
            ViewBag.PagingModel = pagingModel;

            //take paging item
            List<Post> listPosts = pagingModel.TakePagingItem(posts.ToList());

            return View(model: listPosts);
        }

        


        [Route("/post/{postslug}.html")]
        public async Task<IActionResult> Detail([FromRoute(Name = "postslug")] string slug)
        {
            if (slug == null)
            {
                return Content("Not Found a Posts");
            }

            ViewBag.categories = getCategories();

            var post = await _context.Posts
                .Include(p => p.Author)
                .Include(p => p.PostCategories)
                .ThenInclude(p => p.Category)
                .Include(p => p.PostImages)
                .FirstOrDefaultAsync(p => p.Slug == slug);

            ViewBag.category = post.PostCategories.FirstOrDefault()?.Category;


            if (post == null)
            {
                return Content($"Not found a Post have slug: {slug}");
            }

            return View(post);
        }

        public List<Category> getCategories()
        {
            var categories = _context.Categories
                .Include(c => c.CategoryChildren)
                .AsEnumerable()
                .Where(c => c.ParentCategory == null)
                .ToList();
            return categories;
        }
    }
}

AppMVC/Areas/Blog/Views/ViewPost/Detail.cshtml
@using AppMVC.Views.Shared.Component.CategorySideBar
@model Post

@{
    var listCategory = ViewBag.categories as List<Category>;
    var category = ViewBag.category as Category;
    string authorName = Model.Author == null ? "Admin" : Model.Author.Email;
}

<link rel="stylesheet" href="~/css/Product/ViewProduct.css" />


<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="Index" asp-route-categoryslug="">Home</a></li>

        @if (category != null)
        {
            @foreach (var cate in category.GetParentCategories())
            {
                <li class="breadcrumb-item"><a asp-action="Index" asp-route-categoryslug="@cate.Slug">@cate.Title</a></li>
            }
        }
    </ol>
</nav>


<div class="detail">
    <div class="header" >
        <h4> @Model.Title</h4>
        <p>@Model.Description</p>
        <info>
            <p>Author: <strong>@authorName</strong> | Update: @Model.DateUpdated.ToString("d")</p>
            
            @if (Model.PostCategories.Count > 0)
            {
                <p>Categories: </p>

                @foreach (var cate in Model.PostCategories)
                {

                    <p>@cate.Category.Title</p>
                }
            }
            
        </info>
    </div>
    
    <div class="content">
        <div class="content">
            <div class="img">
                @if (Model.PostImages.Any())
                {
                    foreach (var imgPath in Model.PostImages)
                    {
                        <img src="/image/post/@imgPath.FileName" />
                    }
                }
            </div>
            <p>
                @Model.Content
            </p>
        </div>
        <p>
            @Model.Content
        </p>
    </div>
   
</div>

AppMVC/Areas/Blog/Views/ViewPost/Index.cshtml
@model IList<Post>
@using AppMVC.Views.Shared.Component.CategorySideBar
@{
    Category category = ViewBag.category;
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="Index" asp-route-categoryslug="" >Home</a></li>

        @if (category != null)
        {
            @foreach (var cate in category.GetParentCategories())
            {
                <li class="breadcrumb-item"><a asp-action="Index" asp-route-categoryslug="@cate.Slug" >@cate.Title</a></li>
            }
        }
    </ol>
</nav>

@if (category != null)
{
    <div class="text-center show-category">
        <h5>@category.Title</h5>
        <p>@category.Content</p>
    </div>
}


@foreach (var item in Model)
{
    string imagePath = "/image/no-image.png";
    if (item.PostImages.Any())
    {
        imagePath = "/image/post/" + item.PostImages.First().FileName;
    }

    <div class="card mt-3" style="max-width: 100%;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="@imagePath" class="img-fluid rounded-start card-img " alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <a asp-controller="ViewPost" asp-action="Detail" asp-route-postslug="@item.Slug">
                        <h5 class="card-title">@item.Title</h5>
                    </a>
                    <p class="card-text text-muted">@item.Description</p>
                    <p class="card-text text-danger"><small class="text-muted">Author: <strong>@item.Author.UserName</strong> | Updated: <strong>@item.DateUpdated.ToString("d")</strong></small></p>
                </div>
            </div>
        </div>
    </div>
}

<div class="paging-position">
    <partial name="_PagingPartial" model="@ViewBag.PagingModel" />
</div>

AppMVC/Areas/Blog/Views/ViewPost/_BlogLayout.cshtml
@using AppMVC.Views.Shared.Component.CategorySideBar
@using Microsoft.EntityFrameworkCore
@inject AppDBContext _context;
@{
    Layout = "_Layout";
    var listCategory = _context.Categories
                .Include(c => c.CategoryChildren)
                .AsEnumerable()
                .Where(c => c.ParentCategory == null)
                .ToList();
}

@section head{
    <link rel="stylesheet" href="~/css/viewblog/blog_layout.css" />
}

<div class="">
    <div class="row">
        <div class="col-md-3 sidebar">
            <h3 class="text-center title" >
                <a class="cate-index" asp-controller="ViewPost" asp-route-categoryslug="" asp-action="Index">Index Of Category</a>
            </h3>
            @await Component.InvokeAsync("AppMVC.Views.Shared.Component.CategorySideBar.CategorySideBar",
                     new CategorySideBarData()
            {
                level = 0,
                Categories = listCategory,
                slug = ViewBag.slug
            })
        </div>
        <div class="col-md-9 post">
            @RenderBody()
        </div>
    </div>
</div>